name: Publish androidapk newkeystore Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
          ref: dwdw  # hardcoded target branch

    - name: Show current branch
      run: |
          git branch --show-current
          cat ./test.txt
          
    - name: Install certificate
      run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import './Certificatesaaq.p12' -k build.keychain -P "200120080" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

    - name: Install provisioning profile
      run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp 'publishmarre.mobileprovision' ~/Library/MobileDevice/Provisioning\ Profiles/


    
