name: Publish androidapk newkeystore Maui

on:
   workflow_dispatch: # This triggers the workflow manually

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
          ref: dwdw  # hardcoded target branch

    - name: Show current branch
      run: |
          git branch --show-current
          cat ./test.txt



    
